### ISSUE TITLE
Copy chat responses to clipboard

### ISSUE THREAD

**Issue by eduongAZ** [vasilecampeanu/obsidian-weaver#13]
I like to ask ChatGPT to describe something, then copy its response into a note. Right now, I have to manually highlight the text I want to copy, paste it, and manually clean up the formatting.

It would be great if there is a button that copies everything in a response box into clipboard. I can then paste it anywhere I want and modify it.

**Comment by vasilecampeanu** [comment]
Check grammar: Thank you for your feedback. You can expect this feature to be available in the next update. I will be adding an option to enable/disable it in the settings.

**Comment by vasilecampeanu** [comment]
Thank you for your feedback. You can expect this feature to be available in the next update. I will be adding an option to enable/disable it in the settings.

**Comment by vasilecampeanu** [comment]
This feature is now available in version 0.3.2
