### ISSUE TITLE
Buttons using pointer instead of var(--cursor) for cursors

### ISSUE THREAD

**Issue by kepano** [vasilecampeanu/obsidian-weaver#15]
As of Obsidian 1.0 interactive elements should use the `var(--cursor)` variable, which renders as the `default` cursor. The `pointer` cursor should only be used for links.

See
https://forum.obsidian.md/t/1-0-theme-migration-guide/42537#cursor-12

Congrats on launching this plugin, it's fantastic!

**Comment by vasilecampeanu** [comment]
Thank you for your message. The issue you mentioned has been fixed in version 0.3.2. I love the minimal theme, btw <3.
