### ISSUE TITLE
Request cancelled. 

### ISSUE THREAD

**Issue by kmaustral** [vasilecampeanu/obsidian-weaver#17]
It's great to have a plug that is integrated well into Obsidian

When I try to start a chat, I get this response:

>I'm sorry, but I am unable to generate a response at this time. This may be because your request was cancelled, GPT4 is currently in use, or an error has occurred. Please check your settings and try again later.

I disabled Text Generator and re-started, in case this was a problem. I'm using the same API. It works with Text Generator. 

Here's what the console says:
![image](https://user-images.githubusercontent.com/73867063/230850619-90f40033-b759-49ac-9fe7-99b007be66ce.png)

The engine is GPT3.5 Turbo. 

Let me know if there's anything you'd like me to explore further.

**Comment by vasilecampeanu** [comment]
Thanks for pointing this out. Can you please try to install it in the sandbox vault and test it from there?

**Comment by kmaustral** [comment]
Same issue in a sandbox vault. I tried also with a new API. Same error as
before.

**Comment by vasilecampeanu** [comment]
Thank you for that. Please check #20 and [this](https://discord.com/channels/686053708261228577/1094358552463818752), maybe it can help you. From what I found in OpenAI's documentation, this error might be related to your API plan or an issue with an excessive number of requests (which shouldn't happen). I plan to improve request handling, but it will have to wait a couple of days, as I have an exam coming up.

**Comment by kmaustral** [comment]
Hi Vasile,

It turns out my free plan had expired.

I tried Text Generator and it gave an error message with that information.
Curiously, the web interface was still working fine.

I look forward to trying your app now.

Thanks
Kevin

**Comment by vasilecampeanu** [comment]
Thank you for confirming the issue.
