### ISSUE TITLE
Unable to load on iOS

### ISSUE THREAD

**Issue by eduongAZ** [vasilecampeanu/obsidian-weaver#18]
I tried to install the plugin on Obsidian mobile through BRAT, but after BRAT installs it, I cannot enable it in Obsidian community plugin menu.

I pressed the enable toggle button, but it refused to toggle on.

I don't see any error notification, and I don't know how to get the logs to provide you more information.

The only community plugins I have in my vault is BRAT and Weaver (this).

**Comment by vasilecampeanu** [comment]
Hello, this is because I didn't have the time to test it on mobile. I will try to add mobile support in the future.
