### ISSUE TITLE
Load texts being generated as they are generated

### ISSUE THREAD

**Issue by eduongAZ** [vasilecampeanu/obsidian-weaver#19]
It would be great if obsidian displays the text being generated in real time while GPT is generating the text. This allows me to read the message as it is being generated and helps me decide whether I should stop GPT from generating more text.

Currently, the respond box is only loaded after the entire response message is completed. As a user, I feel a little uncomfortable waiting for the message to be completed. I would like to read it while it is being generated.

**Comment by vasilecampeanu** [comment]
Thanks for the feedback, I am going to look into supporting this in a future update.
