### ISSUE TITLE
Consistent error getting responses

### ISSUE THREAD

**Issue by pcuellar** [vasilecampeanu/obsidian-weaver#20]
Since installation and with different models, the plugin keeps returning an error. Here is the return on the chat view and the console. I'm on Obsidian 1.2.2 installer 1.1.9, MacOs Ventura

<img width="396" alt="Screenshot 2023-04-10 at 2 00 26 PM" src="https://user-images.githubusercontent.com/20482146/230963274-d370d4a9-e53f-4093-97ec-103d8307a76f.png">
<img width="522" alt="Screenshot 2023-04-10 at 2 00 57 PM" src="https://user-images.githubusercontent.com/20482146/230963285-7c5612a0-1ee6-42cb-94ec-0429fd761240.png">

**Comment by vasilecampeanu** [comment]
Hello, from what I can tell this issue is not related to the plugin, but rather to your OpenAI API plan. You can find more information about the error [here](https://platform.openai.com/docs/guides/error-codes). Are you using a paid account for the API key?

**Comment by pcuellar** [comment]
Mmm thanks for pointing this out as it led me to discover that OpenAI apparently has set restrictions that pick up on VPNs. Once I turned my VPN off, the request went through.
