### ISSUE TITLE
error message "an error has occurred"

### ISSUE THREAD

**Issue by jsmorabito** [vasilecampeanu/obsidian-weaver#23]
<img width="247" alt="image" src="https://user-images.githubusercontent.com/46250921/232120609-5c8b1cb0-1795-4ea9-aeb6-fc2256b0628b.png">

Hey! I'm getting this error message. I provided my api key from openAI. and the model i have selected in the plugin settings menu is 3.5, not turbo, or 4. Do you have an idea of what could be causing this issue?

**Comment by vasilecampeanu** [comment]
Hello, please check #17. I think it's because your plan for the API key has expired.

**Comment by jsmorabito** [comment]
@vasilecampeanu thank you this was indeed the problem!
