### ISSUE TITLE
Font size too small

### ISSUE THREAD

**Issue by asmagen** [vasilecampeanu/obsidian-weaver#25]
Is there a way to adjust the font to a larger size?
I'm using Minimal theme together with Minimal Theme Settings and Style settings plugins
It's incredibly tiny right now, and any font size settings in obsidian and these plugins doesn't affect it.

**Comment by vasilecampeanu** [comment]
Sorry about that. I plan to include an option for that in a future update, but it may take some time as I am currently focused on reworking how conversations are stored. However, if necessary, you can manually override the font size using a CSS snippet.

**Comment by halr9000** [comment]
As a workaround you should be able to do a quick ctrl-+ and make everything larger.
