### ISSUE TITLE
Clicking on conversation from pane opens the conversation

### ISSUE THREAD

**Issue by TfTHacker** [vasilecampeanu/obsidian-weaver#28]
First, Kudo's. Loving the styling of this plugin.

When clicking on a conversation in the main view, it should open the conversation thread. Currently we have to click on the arrow to open the conversation.

As you can see in the screen grab where I am clicking it seems natural it would open the conversation.

![CleanShot 2023-04-19 at 17 10 21](https://user-images.githubusercontent.com/69121180/233119993-d2848cbc-0783-4198-b8bf-2396acd66f0f.gif)

**Comment by vasilecampeanu** [comment]
I am currently reworking the "home page" for the next release and it doesn't make much sense in the current implementation.

Here is what it looks like now (still working on it):
<img width="459" alt="Screenshot 2023-04-20 at 08 45 53" src="https://user-images.githubusercontent.com/91255194/233269396-d153cd35-40d0-4170-8c0c-df8027bf56ee.png">

But, I am going to add a "compact" setting that will allow for a minimal view of the interface. This mode will let users click directly on the list item.
