### ISSUE TITLE
Set parameters per conversation

### ISSUE THREAD

**Issue by TfTHacker** [vasilecampeanu/obsidian-weaver#29]
Currently we can globally configure the
-  gpt API (ex: 3.5, 4.)
- Prompt
- max tokens
- and so on

It would be super helpful to be able to set the parameters at an individual conversation level. Therefore, if they are not set at the conversation level, the conversation uses the defaults defined in the settings.

If they are defined in the conversation, then they use those specific settings. This can help tweak certain conversations for very specific purposes. For example, I might have one conversation where I want to use the 4.0 API, along with a very specific system role prompt, while another conversation would use the 3.5 API with a very different system role prompt.

4.0 API works better for certain things, especially since it is more sensitive to the system role, whereas 3.5 is good for many things and cheaper.

I know this is a big ask, since each conversation would need to maintain its own configuration and UI for it.

**Comment by vasilecampeanu** [comment]
Thanks for the suggestion. I'll look into adding it, but it may take a couple of weeks to implement since I'm currently busy with exams and my thesis.
