### ISSUE TITLE
Parameter for controlling number of messages sent with each user message

### ISSUE THREAD

**Issue by TfTHacker** [vasilecampeanu/obsidian-weaver#30]
It can be useful to configure how many previous messages in a conversation are sent to the API. In some scenarios, like simple language translation, the history of the conversation does not add any value, but does increase the token count. 

In some other clients I see you can set the number of previous messages (like 0 to 100) to control how many are sent. 

Related to this is the ability to delete various messages from a conversation so as not to resend something that in the end wasn't valuable in the conversation.

**Comment by vasilecampeanu** [comment]
Yah, this is a problem. It's one of the features I want to implement before the community release. I will add a context button for each conversation that will enable this feature. This will also allow you to select individual messages from the conversation to send to the API.
