### ISSUE TITLE
Display the content generated by ChatGPT in real-time

### ISSUE THREAD

**Issue by tk166** [vasilecampeanu/obsidian-weaver#35]
Displaying the content generated in real-time rather than waiting for the whole content can help user to interact with the plug-in more efficiently and save much time in some cases, which feature is provided in the similar plug-in https://github.com/logancyang/obsidian-copilot.  
Leaving the uncomplete content unformated during the generation is just okay I personally think.

**Comment by vasilecampeanu** [comment]
Hello, I'm going to look into it and add that in the next release.

**Comment by vasilecampeanu** [comment]
This is now available in version 0.5.0.

**Comment by tk166** [comment]
Thanks for you great work in such a short time. The final performance is just awesome!
