### ISSUE TITLE
Can't enable the plugin

### ISSUE THREAD

**Issue by 64er** [vasilecampeanu/obsidian-weaver#36]
I can install the plugin manually or via BRAT, but cannot enable it despite restarting Obsidian several times. All other community plugins can be enabled/disabled without problems.

**Comment by vasilecampeanu** [comment]
Is this happening on mobile?

**Comment by 64er** [comment]
Because there was not this red message "The plugin doesn't support your device", I thought it is also suitable for mobile.

**Comment by vasilecampeanu** [comment]
I haven't had time to test it on mobile yet, but it will be coming soon. I need to make sure that the synchronization between the desktop and mobile works properly.
