### ISSUE TITLE
Cannot input text when frame docked at top right corner

### ISSUE THREAD

**Issue by jcoatelen-ledger** [vasilecampeanu/obsidian-weaver#39]
Hi

First, thanks for your great work ! 
I met the following issue which is new after recent update (just updated with BRAT). 

When tab is on main frame, all is fine, but when I the tab is at top right corner I have no access to the text input form.
![image](https://github.com/vasilecampeanu/obsidian-weaver/assets/91121759/b6025a72-9a88-4985-9adb-c7e4f25caca3)
![image](https://github.com/vasilecampeanu/obsidian-weaver/assets/91121759/2a5ba683-c92f-4b89-9dc7-69a0d0671043)

Hope it's sufficient to investigate

**Comment by vasilecampeanu** [comment]
Hello, sorry about that. I think that happens because I set a fixed size for the conversation view. If you close the calendar below and let Weaver occupy the full height of the screen, then the input box should be displayed. I am going to look into it and solve that in the next update.
