### ISSUE TITLE
Can't get in conversition-

### ISSUE THREAD

**Issue by liwenkangatom** [vasilecampeanu/obsidian-weaver#45]
![image](https://github.com/vasilecampeanu/obsidian-weaver/assets/22884346/5e0660ee-3ce0-4e76-a736-63f877a19801)
I configed openai key.but, aways get this page.

**Comment by liwenkangatom** [comment]
no input shows

**Comment by vasilecampeanu** [comment]
The chat view needs to occupy the full height of a pane, so please ensure that nothing else is open. I plan to fix this issue in the future.

**Comment by BumbleBeeElegy** [comment]
> The chat view needs to occupy the full height of a pane, so please ensure that nothing else is open. I plan to fix this issue in the future.

+1 to the issue filed here. I always keep a todo list in my sidebar. So, I have to drag my todo list out of the sidebar every time I want to use the chat function (after I realized why I couldn't start a chat). The Weaver extension should be able to allow for something else to be in the sidebar at the same time and just adjust Weaver's size accordingly (with the ability to scroll all the way to the bottom without having it cut off and not visible).

**Comment by vasilecampeanu** [comment]
A new update will be coming soon, and I will try to address this in that update.
