### ISSUE TITLE
Rate Limited - Fresh Install

### ISSUE THREAD

**Issue by xqsantiidev** [vasilecampeanu/obsidian-weaver#46]
I am getting this error after a fresh install of this plugin.

![image](https://github.com/vasilecampeanu/obsidian-weaver/assets/130874019/1acc914f-ec6f-458f-ab9e-2542c862f48e)

I have all the settings to the default except my api key. Any help would be very much appreciated.

**Comment by vasilecampeanu** [comment]
Apologies for the wait. As stated, you should check your plan for the API key on the OpenAI platform and see if it is still active.

**Comment by xqsantiidev** [comment]
No problem! I have a free account to use chat gpt. Do I need to pay for a API key that I can use with weaver?

**Comment by xqsantiidev** [comment]
Could it be another plugin that is breaking it?

**Comment by vasilecampeanu** [comment]
You have 30 days of free access to the API. The API is separate from the ChatGPT account.

**Comment by xqsantiidev** [comment]
I see. But I just created the API. Shouldnt I be able to use it for 30 days then?
