### ISSUE TITLE
Use Weaver without an OpenAI key for privacy

### ISSUE THREAD

**Issue by valgameiroconsulting** [vasilecampeanu/obsidian-weaver#48]
Using a key links all your searches and responses to an identity. Requests will always be linked with an IP address, but that address is shared in most cases. I'd love to use the plugin but don't want to create a key and add my identity to big metadata bucket in the sky. Any chance of modifying the plugin to not use an API key, even at the loss of some functionality?

**Comment by vasilecampeanu** [comment]
Sorry for the late response. I'm working on a refactor and considering adding support for locally-hosted models, but it's going to take some time. Thanks for bringing up the issue.
